/*
 * generated by Xtext 2.11.0.RC2
 */
package org.xtext.ufcg.compiladores.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class PascalScopeProvider extends AbstractPascalScopeProvider {

}
