/*
 * generated by Xtext 2.11.0.RC2
 */
package org.xtext.ufcg.compiladores


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PascalStandaloneSetup extends PascalStandaloneSetupGenerated {

	def static void doSetup() {
		new PascalStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
