package org.xtext.ufcg.compiladores.validation;

public enum ErrorType {

	REDECLARATION, NOT_DECLARATION, CONSTANT_ASSIGNMENT, CONSTANT_ONLY, 
	FUNCTION_ONLY, TYPE_CONVERSION_ERROR, UNDEFINED_TYPE, INVALID_OPERATOR, 
	NOT_ARRAY, NOT_INITIALIZED, TYPE_COHESION, CASE_LIMB_REPEATED
	
}