/*
 * generated by Xtext 2.10.0
 */
package org.xtext.ufcg.compiladores.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPascalScopeProvider extends DelegatingScopeProvider {
}
