/**
 * generated by Xtext 2.11.0.RC2
 */
package org.xtext.ufcg.compiladores.scoping;

import org.xtext.ufcg.compiladores.scoping.AbstractPascalScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class PascalScopeProvider extends AbstractPascalScopeProvider {
}
