/**
 * generated by Xtext 2.11.0
 */
package org.xtext.ufcg.compiladores.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>bound specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.bound_specification#getInit <em>Init</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.bound_specification#getFin <em>Fin</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.bound_specification#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getbound_specification()
 * @model
 * @generated
 */
public interface bound_specification extends EObject
{
  /**
   * Returns the value of the '<em><b>Init</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Init</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init</em>' attribute.
   * @see #setInit(String)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getbound_specification_Init()
   * @model
   * @generated
   */
  String getInit();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.bound_specification#getInit <em>Init</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init</em>' attribute.
   * @see #getInit()
   * @generated
   */
  void setInit(String value);

  /**
   * Returns the value of the '<em><b>Fin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fin</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fin</em>' attribute.
   * @see #setFin(String)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getbound_specification_Fin()
   * @model
   * @generated
   */
  String getFin();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.bound_specification#getFin <em>Fin</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fin</em>' attribute.
   * @see #getFin()
   * @generated
   */
  void setFin(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getbound_specification_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.bound_specification#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // bound_specification
