/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ufcg.compiladores.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>for statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.for_statement#getInitID <em>Init ID</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.for_statement#getExpressionInit <em>Expression Init</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.for_statement#getExpressionFin <em>Expression Fin</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.for_statement#getStmt <em>Stmt</em>}</li>
 * </ul>
 *
 * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getfor_statement()
 * @model
 * @generated
 */
public interface for_statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Init ID</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Init ID</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init ID</em>' attribute.
   * @see #setInitID(String)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getfor_statement_InitID()
   * @model
   * @generated
   */
  String getInitID();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.for_statement#getInitID <em>Init ID</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init ID</em>' attribute.
   * @see #getInitID()
   * @generated
   */
  void setInitID(String value);

  /**
   * Returns the value of the '<em><b>Expression Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression Init</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression Init</em>' containment reference.
   * @see #setExpressionInit(expression)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getfor_statement_ExpressionInit()
   * @model containment="true"
   * @generated
   */
  expression getExpressionInit();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.for_statement#getExpressionInit <em>Expression Init</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression Init</em>' containment reference.
   * @see #getExpressionInit()
   * @generated
   */
  void setExpressionInit(expression value);

  /**
   * Returns the value of the '<em><b>Expression Fin</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression Fin</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression Fin</em>' containment reference.
   * @see #setExpressionFin(expression)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getfor_statement_ExpressionFin()
   * @model containment="true"
   * @generated
   */
  expression getExpressionFin();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.for_statement#getExpressionFin <em>Expression Fin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression Fin</em>' containment reference.
   * @see #getExpressionFin()
   * @generated
   */
  void setExpressionFin(expression value);

  /**
   * Returns the value of the '<em><b>Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmt</em>' containment reference.
   * @see #setStmt(statement)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getfor_statement_Stmt()
   * @model containment="true"
   * @generated
   */
  statement getStmt();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.for_statement#getStmt <em>Stmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stmt</em>' containment reference.
   * @see #getStmt()
   * @generated
   */
  void setStmt(statement value);

} // for_statement
