/**
 * generated by Xtext 2.11.0
 */
package org.xtext.ufcg.compiladores.pascal;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>structured statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.structured_statement#getCompound <em>Compound</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.structured_statement#getRepetitive <em>Repetitive</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.structured_statement#getConditional <em>Conditional</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.structured_statement#getWith_stt <em>With stt</em>}</li>
 * </ul>
 *
 * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getstructured_statement()
 * @model
 * @generated
 */
public interface structured_statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Compound</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Compound</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Compound</em>' containment reference.
   * @see #setCompound(compound_statement)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getstructured_statement_Compound()
   * @model containment="true"
   * @generated
   */
  compound_statement getCompound();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.structured_statement#getCompound <em>Compound</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Compound</em>' containment reference.
   * @see #getCompound()
   * @generated
   */
  void setCompound(compound_statement value);

  /**
   * Returns the value of the '<em><b>Repetitive</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Repetitive</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Repetitive</em>' containment reference.
   * @see #setRepetitive(repetitive_statement)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getstructured_statement_Repetitive()
   * @model containment="true"
   * @generated
   */
  repetitive_statement getRepetitive();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.structured_statement#getRepetitive <em>Repetitive</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Repetitive</em>' containment reference.
   * @see #getRepetitive()
   * @generated
   */
  void setRepetitive(repetitive_statement value);

  /**
   * Returns the value of the '<em><b>Conditional</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Conditional</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Conditional</em>' containment reference.
   * @see #setConditional(conditional_statement)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getstructured_statement_Conditional()
   * @model containment="true"
   * @generated
   */
  conditional_statement getConditional();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.structured_statement#getConditional <em>Conditional</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Conditional</em>' containment reference.
   * @see #getConditional()
   * @generated
   */
  void setConditional(conditional_statement value);

  /**
   * Returns the value of the '<em><b>With stt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>With stt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>With stt</em>' containment reference.
   * @see #setWith_stt(with_statement)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getstructured_statement_With_stt()
   * @model containment="true"
   * @generated
   */
  with_statement getWith_stt();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.structured_statement#getWith_stt <em>With stt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>With stt</em>' containment reference.
   * @see #getWith_stt()
   * @generated
   */
  void setWith_stt(with_statement value);

} // structured_statement
