/**
 * generated by Xtext 2.10.0
 */
package org.xtext.ufcg.compiladores.pascal;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>with statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.with_statement#getRecord <em>Record</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.with_statement#getRecords <em>Records</em>}</li>
 *   <li>{@link org.xtext.ufcg.compiladores.pascal.with_statement#getStmt <em>Stmt</em>}</li>
 * </ul>
 *
 * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getwith_statement()
 * @model
 * @generated
 */
public interface with_statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Record</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Record</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Record</em>' attribute.
   * @see #setRecord(String)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getwith_statement_Record()
   * @model
   * @generated
   */
  String getRecord();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.with_statement#getRecord <em>Record</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Record</em>' attribute.
   * @see #getRecord()
   * @generated
   */
  void setRecord(String value);

  /**
   * Returns the value of the '<em><b>Records</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Records</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Records</em>' attribute list.
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getwith_statement_Records()
   * @model unique="false"
   * @generated
   */
  EList<String> getRecords();

  /**
   * Returns the value of the '<em><b>Stmt</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stmt</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stmt</em>' containment reference.
   * @see #setStmt(statement)
   * @see org.xtext.ufcg.compiladores.pascal.PascalPackage#getwith_statement_Stmt()
   * @model containment="true"
   * @generated
   */
  statement getStmt();

  /**
   * Sets the value of the '{@link org.xtext.ufcg.compiladores.pascal.with_statement#getStmt <em>Stmt</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stmt</em>' containment reference.
   * @see #getStmt()
   * @generated
   */
  void setStmt(statement value);

} // with_statement
