/**
 * generated by Xtext 2.11.0.RC2
 */
package org.xtext.ufcg.compiladores.tests;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.xtext.ufcg.compiladores.pascal.program;
import org.xtext.ufcg.compiladores.tests.PascalInjectorProvider;

/* @RunWith(/* name is null */)
@InjectWith(PascalInjectorProvider.class) */@SuppressWarnings("all")
public class PascalParsingTest {
  /* @Inject
   */private /* ParseHelper<program> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field PascalParsingTest.parseHelper refers to the missing type ParseHelper"
      + "\nparse cannot be resolved"
      + "\neResource cannot be resolved"
      + "\nerrors cannot be resolved"
      + "\nisEmpty cannot be resolved");
  }
}
