/**
 * generated by Xtext 2.11.0.RC2
 */
package org.xtext.ufcg.compiladores;

import org.xtext.ufcg.compiladores.PascalStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class PascalStandaloneSetup extends PascalStandaloneSetupGenerated {
  public static void doSetup() {
    new PascalStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
