/**
 * generated by Xtext 2.11.0.RC2
 */
package org.xtext.ufcg.compiladores.ide;

import com.google.inject.Injector;
import org.xtext.ufcg.compiladores.PascalStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class PascalIdeSetup extends PascalStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from PascalIdeModule to Module");
  }
}
