/**
 * generated by Xtext 2.11.0.RC2
 */
package org.xtext.ufcg.compiladores.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PascalIdeModule /* implements AbstractPascalIdeModule  */{
}
